# configs/config_v50.yaml
# SpectraMind V50 – Main Hydra config (fits your folder names)

defaults:
  - data: v50
  - model: v50
  - training: v50
  - diagnostics: v50
  - logging: v50
  - repro: v50
  - paths: v50
  - _self_

project:
  name: "SpectraMindV50"
  tag: "default"
  run_mode: "train"   # [train|predict|diagnose]
  fold: 0
  timestamp: ${now:%Y-%m-%d_%H-%M-%S}

toggles:
  use_corel: true
  use_symbolic_losses: true
  save_intermediate_artifacts: true
  browser_open_reports: false

hydra:
  run:
    dir: outputs/${project.name}/${project.tag}/${project.run_mode}/${project.timestamp}
  sweep:
    dir: sweeps/${project.name}/${project.tag}/${project.run_mode}/${project.timestamp}
  job:
    chdir: true