name: SpectraMind V50 CI
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Selftest
        run: python -m src.spectramind.cli.selftest
      - name: Smoke Train
        run: python -m spectramind train --epochs 1 --lr 3e-4
      - name: Smoke Predict + Dashboard
        run: |
          python -m spectramind predict --out-csv outputs/submission.csv
          python -m spectramind dashboard --html outputs/diagnostics/diagnostic_report_v50.html
      - name: Upload Diagnostics
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics
          path: outputs/diagnostics
